services:
  healf-fastapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/healf_db"
    networks:
      - healf-app-network
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healf_db
    volumes:
      - "./db/postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - healf-app-network

networks:
  healf-app-network:
    driver: bridge 