services:
  healf-fastapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    command: ["/app/.venv/bin/fastapi", "dev", "app/main.py", "--port", "80", "--host", "0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: Dockerfile
    platform: linux/amd64