services:
  healf-fastapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["/app/.venv/bin/fastapi", "dev", "app/main.py", "--port", "80", "--host", "0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile
    platform: linux/amd64
    networks:
      - healf-app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healf_db
    volumes:
      - "./db/postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - healf-app-network

networks:
  healf-app-network:
    driver: bridge 