services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - healf-fastapi
    networks:
      - healf-app-network

  healf-fastapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - /app/.venv
    env_file:
      - .env
    platform: linux/amd64
