[project]
name = "healf-llm-backend-ws-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.12"

dependencies = [
    "fastapi[standard]==0.115.12",
    "llama-index==0.12.39",
    "websockets==15.0.1",
]
